<template>
	<div class="root">
		<div :class="['container', {loading}]">
			<div class="header">ZeroNet Instant Messenger</div>
			<div class="text">No more 30 seconds delay. Fullstop.</div>
			<button class="start" @click="start">Start chatting</button>
		</div>
	</div>
</template>

<style lang="sass" scoped>
	$time: 5s

	.root
		width: 100%
		height: 100%

		background-color: #000

		opacity: 1
		transition: opacity 0.5s

	.container
		width: 100%
		height: 200%
		padding: 0 16px
		padding-top: 100vh

		// Ease-in gradient generated by https://larsenwork.com/easing-gradients/
		background: linear-gradient(to bottom, hsl(202.18, 72.51%, 0%) 0%, hsl(202.18, 72.51%, 2.9%) 5%, hsl(202.18, 72.51%, 5.95%) 9.9%, hsl(202.18, 72.51%, 9.16%) 14.8%, hsl(202.18, 72.51%, 12.55%) 19.7%, hsl(202.18, 72.51%, 16.1%) 24.3%, hsl(202.18, 72.51%, 19.85%) 28.9%, hsl(202.18, 72.51%, 23.73%) 33.1%, hsl(202.18, 72.51%, 27.68%) 37%, hsl(202.18, 72.51%, 31.67%) 40.4%, hsl(202.18, 72.51%, 35.6%) 43.2%, hsl(202.18, 72.51%, 39.42%) 45.6%, hsl(202.18, 72.51%, 43.19%) 50%, hsl(202.18, 72.51%, 46.67%) 60%, hsl(202.18, 72.97%, 50.16%) 70%, hsl(202.18, 83.94%, 53.65%) 80%, hsl(202.18, 96.35%, 57.06%) 90%, hsl(202.18, 96.35%, 57.06%) 100%)

		display: flex
		flex-direction: column
		justify-content: center
		align-items: center

		transform: translateY(100%)
		transition: transform $time ease-in-out
	.loading
		transform: translateY(-50%)


	.header
		margin-bottom: 32px

		font-family: Impact, Verdana, Arial, sans-serif
		font-size: 64px
		line-height: 72px
		letter-spacing: 2px
		word-spacing: 16px
		text-align: center
		color: #FFF

	.text
		font-size: 32px
		line-height: 48px
		text-align: center
		color: #FFF


	.start
		display: inline-block
		padding: 16px 24px
		margin-top: 16px

		font-size: 24px
		color: #FFF

		border: none
		background-color: darken(hsl(202.18, 96.35%, 57.06%), 30%)
		border-radius: 8px
		cursor: pointer

		transition: background-color 0.5s

	.start:hover
		background-color: darken(hsl(202.18, 96.35%, 57.06%), 50%)
</style>

<script type="text/javascript">
	import {zeroAuth} from "route.js";

	export default {
		name: "login-page",
		data() {
			return {
				loading: false
			};
		},

		mounted() {
			setTimeout(() => {
				this.loading = true;
			}, 0);
		},

		methods: {
			start() {
				zeroAuth.requestAuth();
			}
		}
	};
</script>